import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
      <nav className="navbar flex flex-row items-center gap-2 bg-base-100 p-2">
        <img src="/kipi-dashboard/logo.svg" className="h-12" alt="logo" />
        <a className="btn btn-ghost text-xl">Kipi Interactive Dashboard</a>
      </nav>
      {children}
      </body>
    </html>
  );
}
